import { inviteBefore } from './invite/view.js';
const button = (label, next, kind = 'primary') => `<button class="ui-button ${kind}" type="button" data-transition="${next}">${label}</button>`;
const status = (label, tone = 'neutral') => `<span class="ui-status ${tone}">${label}</span>`;
const beforeNotice = state => ({loading:'Loading...',error:'Something went wrong. Try again.',success:'Done!',permission:'Unavailable',stale:'Last update unavailable',empty:'No data'}[state] || '');
const beforeState = state => state === 'default' ? '' : `<div class="bad-notice">${beforeNotice(state)}</div>`;
const panel = (title, body, className = '') => `<section class="ui-panel ${className}"><h3>${title}</h3>${body}</section>`;

function invite(state, before) {
  return before ? inviteBefore(state) : '<div class="invite-host"></div>';
}

function dashboard(state, before) {
  if (before) return `<div class="mock bad dashboard-bad"><header class="bad-top">FLOW OPS <span>Dashboard &nbsp; Analytics &nbsp; Settings</span></header><div class="bad-inner"><h2>Good morning, Alex 👋</h2><p>Here is what is happening today</p>${beforeState(state)}<div class="bad-metrics"><div>Orders<br><b>1,284</b><small>↗ 12.4%</small></div><div>Revenue<br><b>$48.2k</b><small>↗ 8.2%</small></div><div>Activity<br><b>92%</b><small>All good!</small></div></div><div class="bad-chart">Overview <div class="chart-bars">▂ ▆ ▃ ▇ ▅ ▄ ▆ ▂ ▇ ▄ ▆</div></div><div class="bad-list">Recent activity <span>View all →</span><p>Route 17 &nbsp; · &nbsp; Late handoff &nbsp; 08:42</p></div></div></div>`;
  let alert = state === 'stale' ? ['Data may be out of date', 'Last synced at 08:42. Reconnect before making dispatch decisions.', 'warn'] : state === 'error' ? ['Live data unavailable', 'Route records could not refresh. The last known snapshot is shown below.', 'danger'] : state === 'loading' ? ['Refreshing routes', 'Checking dispatch updates for Amman North…', 'info'] : state === 'route' ? ['Route 17 · South loop', 'Driver: Omar Saleh · 3 affected deliveries · next handoff: Sweifieh at 09:24.', 'info'] : state === 'empty' ? ['No routes for this view', 'No dispatches match Amman North today. Change the region or date.', 'info'] : null;
  return `<div class="mock product ops"><aside class="ops-side"><b class="ops-logo">◈ <span>flowline</span></b><nav><span class="selected">Overview</span><span>Routes</span><span>Orders</span><span>Team</span></nav><small>AMMAN NORTH<br>Operations workspace</small></aside><div class="ops-main"><header class="ops-toolbar"><span>Operations / Overview</span><span>${status(state === 'stale' || state === 'error' ? 'Snapshot · 08:42' : 'Synced · 09:18', state === 'stale' || state === 'error' ? 'warn' : 'good')}</span></header><div class="ops-body"><div class="product-kicker">THURSDAY, 24 SEPTEMBER · AMMAN NORTH</div><h2>Today’s dispatch</h2><p class="muted">Exceptions first. 24 routes scheduled, 21 on time.</p>${alert ? `<div class="inline-banner ${alert[2]}" role="status"><strong>${alert[0]}</strong><span>${alert[1]}</span>${state !== 'empty' ? button('Refresh view','default','secondary') : ''}</div>` : ''}${state !== 'empty' ? `<div class="ops-highlight"><div><div class="product-kicker">NEEDS ATTENTION · ROUTE 17</div><h3>Handoff is 36 min late</h3><p>Driver has not checked in at Sweifieh. Three deliveries may miss the promised window.</p></div><div class="ops-highlight-side"><span>08:42 expected</span>${button('Show route details','route')}</div></div><div class="ops-stats"><div><span>On time</span><strong>21 <small>/ 24</small></strong></div><div><span>At risk</span><strong>03</strong></div><div><span>Delivered</span><strong>186</strong></div></div>${panel('Routes requiring review', `<div class="ops-row head"><span>ROUTE</span><span>AREA</span><span>STATUS</span><span>LAST UPDATE</span></div><div class="ops-row"><strong>17 · South loop</strong><span>Sweifieh</span>${status('Late handoff','danger')}<span>08:42</span></div><div class="ops-row"><strong>09 · City centre</strong><span>Abdali</span>${status('At risk','warn')}<span>09:02</span></div><div class="ops-row"><strong>22 · West route</strong><span>Khalda</span>${status('At risk','warn')}<span>09:11</span></div>`)}` : panel('No dispatches found', '<p class="muted">Try a different region or date to see scheduled routes.</p>')}</div></div></div>`;
}

function pos(state, before) {
  if (before) return `<div class="mock bad pos-bad"><header class="bad-top">STORELY POS <span>Register 02 &nbsp; • &nbsp; Menu</span></header><div class="pos-bad-grid"><div><h2>New sale</h2><p>Popular items</p><div class="bad-products"><div>☕<br>Flat white<br>$4.50</div><div>🥐<br>Croissant<br>$3.75</div><div>🥪<br>Sandwich<br>$8.00</div></div><div class="bad-card">Your cart is ready ✨</div></div><div class="bad-card"><h3>Order summary</h3>${beforeState(state)}<p>Flat white x2 <span>$9.00</span></p><p>Croissant x1 <span>$3.75</span></p><hr><p>Total <b>$13.16</b></p><button class="bad-btn">Charge $13.16</button><small>Secure checkout powered by Storely</small></div></div></div>`;
  const note = {loading:['Waiting for terminal','Keep this sale open. The simulated terminal has not returned an outcome.','info'],error:['Payment did not complete','No charge is recorded in this demo. Check the terminal and retry once.','danger'],success:['Sale completed · demo','Receipt #S-2048 is ready. This is a simulated transaction.','good'],permission:['Manager approval required','Refunds require a manager. This cashier can continue the current sale.','warn']}[state];
  return `<div class="mock product pos"><header class="pos-top"><b>COMMON / GROUND</b><span>Register 02 · Amman</span>${status('Open shift','good')}</header><div class="pos-layout"><div class="pos-menu"><div class="product-kicker">COUNTER / NEW SALE</div><h2>New sale</h2><p class="muted">Select an item to add it to the basket.</p><div class="pos-products"><div><span>01</span><strong>Flat white</strong><small>12 oz · Espresso</small><b>$4.50</b></div><div><span>02</span><strong>Butter croissant</strong><small>Baked today</small><b>$3.75</b></div><div><span>03</span><strong>Turkey sandwich</strong><small>Cold kitchen</small><b>$8.00</b></div><div><span>04</span><strong>Filter coffee</strong><small>House blend</small><b>$3.25</b></div></div></div><div class="pos-receipt"><div class="receipt-heading"><div><div class="product-kicker">ORDER #2048</div><h3>Current sale</h3></div><span>3 items</span></div>${note ? `<div class="inline-banner ${note[2]}" role="status"><strong>${note[0]}</strong><span>${note[1]}</span></div>` : ''}<div class="receipt-line"><span>2 × Flat white</span><b>$9.00</b></div><div class="receipt-line"><span>1 × Butter croissant</span><b>$3.75</b></div><div class="receipt-totals"><div><span>Subtotal</span><b>$12.75</b></div><div><span>Discount · morning special</span><b>−$1.50</b></div><div><span>Tax · 17%</span><b>$1.91</b></div></div><div class="receipt-total"><span>Amount due</span><strong>$13.16</strong></div><div class="receipt-action">${state === 'loading' ? button('Complete simulated payment','success') : state === 'error' ? button('Retry payment','loading') : state === 'success' ? button('New sale','default') : button('Charge $13.16','loading')}<small>Demo register · no payment is processed</small></div></div></div></div>`;
}

function booking(state, before) {
  if (before) return `<div class="mock bad booking-bad"><header class="bad-top">STILLWELL <span>Services &nbsp; About &nbsp; Book</span></header><div class="bad-book"><h2>Book your appointment ✨</h2><p>Choose your perfect time</p>${beforeState(state)}<div class="bad-calendar">SEPTEMBER 2026<br><br>MON &nbsp; TUE &nbsp; WED &nbsp; THU &nbsp; FRI<br><br>21 &nbsp;&nbsp; 22 &nbsp;&nbsp; 23 &nbsp;&nbsp; <b>24</b> &nbsp;&nbsp; 25</div><div class="bad-times"><span>09:00</span><span class="active">10:30</span><span>11:00</span></div><input value="Rania Haddad" readonly><input value="rania@example.com" readonly><button class="bad-btn">Confirm booking →</button></div></div>`;
  const note = {loading:['Checking the appointment','We are rechecking this time before showing a simulated confirmation.','info'],stale:['10:30 is no longer available','Your details are saved in this demo. Choose 11:00 or 11:30 to continue.','warn'],error:['Could not check availability','Your name and email are still here. Retry the check before confirming.','danger'],success:['Appointment held · demo','Thursday 24 September at 11:00. Reference SW-4821 is simulated.','good']}[state];
  return `<div class="mock product booking"><header class="booking-top"><b>STILLWELL<span> / </span>CLINIC</b><span>Appointments &nbsp; Care team</span></header><div class="booking-content"><div class="product-kicker">NEW APPOINTMENT / STEP 2 OF 2</div><h2>Choose a time that works.</h2><p class="muted">Consultation with Dr Lina Faris · 30 minutes · Amman clinic</p>${note ? `<div class="inline-banner ${note[2]}" role="status"><strong>${note[0]}</strong><span>${note[1]}</span></div>` : ''}<div class="booking-grid">${panel('Thursday, 24 September', `<div class="booking-date"><span>WED<br><b>23</b></span><span class="picked">THU<br><b>24</b></span><span>FRI<br><b>25</b></span></div><p class="field-help">Times shown in Amman time (UTC+3)</p><div class="time-slots"><span>09:00</span><span class="${state === 'stale' ? 'unavailable' : state === 'default' ? 'selected' : ''}">10:30 ${state === 'stale' ? '· taken' : ''}</span><span class="${state === 'default' ? '' : 'selected'}">11:00</span><span>11:30</span></div>`) }${panel('Your details', `<div class="detail-field"><small>NAME</small><strong>Rania Haddad</strong></div><div class="detail-field"><small>EMAIL</small><strong dir="ltr">rania@example.com</strong></div><div class="detail-field"><small>VISIT</small><strong>First consultation</strong></div>`)}</div><div class="form-footer"><span>No real appointment is created</span>${state === 'loading' ? button('Finish simulated check','success') : state === 'success' ? button('Book another visit','default','secondary') : state === 'error' ? button('Retry availability check','loading') : state === 'default' ? button('Check 10:30 availability','stale') : button('Continue with 11:00','loading')}</div></div></div>`;
}

function arabic(state, before) {
  if (before) return `<div class="mock bad arabic-bad" dir="rtl" lang="ar"><header class="bad-top">إدارة بلس <span>Dashboard &nbsp; Settings</span></header><div class="bad-inner"><h2>أهلاً بك في لوحة التحكم ✨</h2><p>إليك آخر التحديثات</p>${beforeState(state)}<div class="bad-metrics"><div>الطلبات<br><b>1,284</b></div><div>المستخدمون<br><b>427</b></div></div><div class="bad-card"><h3>طلبات الوصول</h3><p>طلب جديد من maya@northstar.co #REQ-2048</p><button class="bad-btn">موافقة →</button></div></div></div>`;
  const note = {loading:['جارٍ تحديث الطلبات','نراجع أحدث طلبات الوصول.','info'],error:['تعذّر تحديث الطلبات','البيانات المعروضة من آخر مزامنة. أعد المحاولة.','danger'],success:['تمت مراجعة الطلب · عرض تجريبي','حُدّثت حالة الطلب REQ-2048 في هذا العرض فقط.','good'],permission:['لا تملك صلاحية الموافقة','يمكنك عرض الطلبات. اطلب من مدير المساحة مراجعة هذا الطلب.','warn']}[state];
  return `<div class="mock product arabic" dir="rtl" lang="ar"><aside class="arabic-side"><b>مِعيار <i>✳</i></b><nav><span>نظرة عامة</span><span class="selected">طلبات الوصول</span><span>الأعضاء</span><span>الإعدادات</span></nav><small>مساحة العمل<br>الفرع الرئيسي · عمّان</small></aside><div class="arabic-main"><header><span>مساحة العمل / طلبات الوصول</span>${status('آخر تحديث ٠٩:١٨','good')}</header><div class="arabic-body"><div class="product-kicker">إدارة الصلاحيات / ٢٤ سبتمبر ٢٠٢٦</div><h2>طلبات الوصول</h2><p class="muted">راجع الطلبات المعلّقة قبل منح صلاحيات التحرير.</p>${note ? `<div class="inline-banner ${note[2]}" role="status"><strong>${note[0]}</strong><span>${note[1]}</span>${state === 'error' ? button('إعادة المحاولة','default','secondary') : ''}</div>` : ''}<div class="arabic-summary"><div><small>بانتظار المراجعة</small><strong>٠٣</strong></div><div><small>تمت مراجعتها اليوم</small><strong>١٢</strong></div></div>${panel('طلبات تحتاج إلى قرار', `<div class="arabic-request"><div class="request-person"><span class="avatar">MC</span><div><strong>مايا تشن</strong><small dir="ltr">maya@northstar.co</small></div></div><div><small>رقم الطلب</small><code dir="ltr">REQ-2048</code></div><div><small>الصلاحية المطلوبة</small><strong>محرّر محتوى</strong></div><div class="request-action">${state === 'permission' ? button('طلب مراجعة المدير','default','secondary') : state === 'loading' ? button('إكمال المراجعة التجريبية','success') : state === 'success' ? status('تمت المراجعة','good') : button('مراجعة الطلب','loading')}</div></div><div class="arabic-request secondary"><div class="request-person"><span class="avatar">LK</span><div><strong>ليان كريم</strong><small dir="ltr">layan@example.org</small></div></div><div><small>رقم الطلب</small><code dir="ltr">REQ-2051</code></div><div><small>الصلاحية المطلوبة</small><strong>مشاهد</strong></div><div>${status('بانتظار المراجعة','warn')}</div></div>`)}</div></div></div>`;
}

function deslop(state, before) {
  if (before) return `<div class="mock bad deslop-bad"><header class="bad-top">folio<span>☼</span> <small>Dashboard &nbsp; Invoices &nbsp; Reports &nbsp; Settings</small></header><div class="bad-inner"><h2>Welcome back, Jordan! ✨</h2><p>Here’s your financial overview</p>${beforeState(state)}<div class="bad-metrics"><div>💸 Total revenue<br><b>$124,850</b><small>↗ 24%</small></div><div>📈 Outstanding<br><b>$18,420</b><small>12 invoices</small></div><div>🎉 Paid<br><b>89%</b><small>Great job!</small></div></div><div class="bad-card"><h3>Invoice performance</h3><div class="chart-bars">▂ ▆ ▃ ▇ ▅ ▄ ▆ ▂ ▇ ▄ ▆</div></div><div class="bad-card"><h3>Recent invoices</h3>INV-2408 &nbsp; Crescent Studio &nbsp; $4,800 <button>View →</button></div></div></div>`;
  const note = {loading:['Refreshing invoices','Retrieving the current invoice list for September.','info'],error:['Invoices could not refresh','The last saved view is still available. Retry to check for updates.','danger'],success:['Review marked complete · demo','Invoice INV-2408 has been marked reviewed in this browser session.','good'],empty:['No invoices in this view','Try a different month or clear the status filter.','info']}[state];
  return `<div class="mock product deslop"><header class="folio-top"><b>folio<span>☼</span></b><nav><span>Overview</span><span class="active">Invoices</span><span>Clients</span><span>Reports</span></nav><span class="avatar">JD</span></header><div class="folio-body"><div class="product-kicker">BILLING / SEPTEMBER 2026</div><div class="folio-heading"><div><h2>Invoices</h2><p class="muted">Review what needs attention before the month closes.</p></div><span>12 open · USD</span></div>${note ? `<div class="inline-banner ${note[2]}" role="status"><strong>${note[0]}</strong><span>${note[1]}</span>${state === 'error' ? button('Retry refresh','default','secondary') : ''}</div>` : ''}<div class="folio-overview"><div><small>OUTSTANDING</small><strong>$18,420<span>.00</span></strong><p>Across 12 open invoices</p></div><div><small>NEEDS REVIEW</small><strong>03</strong><p>Before sending reminders</p></div></div><div class="folio-list-head"><h3>${state === 'empty' ? 'No invoices found' : 'Needs your review'}</h3><span>Showing September · Open</span></div>${state === 'empty' ? `<div class="folio-empty">There are no open invoices for this selection.</div>` : `<div class="folio-row"><div class="folio-id"><strong>INV-2408</strong><span>Crescent Studio · due 28 Sep</span></div><div class="folio-value"><strong>$4,800.00</strong>${status(state === 'success' ? 'Reviewed' : 'Review due', state === 'success' ? 'good' : 'warn')}</div>${state === 'loading' ? button('Finish refresh','default','secondary') : state === 'success' ? button('Review next','default','secondary') : button('Review invoice','success','secondary')}</div><div class="folio-row"><div class="folio-id"><strong>INV-2399</strong><span>Fieldwork Co. · due 30 Sep</span></div><div class="folio-value"><strong>$2,150.00</strong>${status('Draft','neutral')}</div><span class="folio-row-note">Awaiting approval</span></div>`}<div class="folio-foot">Folio billing · all outcomes in this showcase are simulated</div></div></div>`;
}

const renderers = { 'invite-team':invite, 'operations-dashboard':dashboard, 'pos-checkout':pos, 'booking-recovery':booking, 'arabic-admin-rtl':arabic, 'visual-deslop':deslop };
export function screen(id, state, before = false) { return renderers[id](state, before); }
